# title of website
title: nav

# description of website
description: irislan425-cell's navigation site

# favicon of website
favicon: "https://github.com/irislan425-cell.png?size=40"

# your website url
url: https://irislan425-cell.github.io/nav/

# github profile url
github: "https://github.com/irislan425-cell"

# footer message
footer: © 2021-2021 @irislan425-cell

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: Dribbble
          description: 全球UI设计师作品分享平台。
          url: https://dribbble.com/
        - name: Behance
          description: Adobe旗下的设计师交流平台，来自世界各地的设计师在这里分享自己的作品。
          url: https://behance.net/
        - name: 站酷
          description: 中国人气设计师互动平台
          url: http://www.zcool.com.cn/
        - name: Pinterest
          description: 全球美图收藏采集站
          url: https://www.pinterest.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 优设
          description: 设计师交流学习平台
          url: http://www.uisdc.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
    - name: 图标素材
      sites:
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: http://www.iconfont.cn/
        - name: iconmonstr
          description: Free simple icons for your next project
          url: https://iconmonstr.com/
    - name: 设计模板网站
      sites:
        - name: 千图网
          description: 专注免费设计素材下载的网站
          url: http://www.58pic.com/
        - name: 千库网
          description: 免费png图片背景素材下载
          url: http://588ku.com/
        - name: 我图网
          description: 我图网,提供图片素材及模板下载,专注正版设计作品交易
          url: http://www.ooopic.com/
        - name: 90设计
          description: 电商设计（淘宝美工）千图免费淘宝素材库
          url: http://90sheji.com/
        - name: 昵图网
          description: 原创素材共享平台
          url: http://www.nipic.com/
    - name: 字体资源
      sites:
        - name: 识字体网
          description: 在线图片字体识别扫一扫网站
          url: https://www.likefont.com/
        - name: Google Font
          description: Making the web more beautiful, fast, and open through great typography
          url: https://fonts.google.com/
        - name: FontM
          description: Free Fonts
          url: http://fontm.com/
        - name: Da Font
          description: Archive of freely downloadable fonts.
          url: https://www.dafont.com/
    - name: 图库素材
      sites:
        - name: freepik
          description: More than a million free vectors, PSD, photos and free icons.
          url: https://www.freepik.com/
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: StockSnap
          description: Beautiful free stock photos
          url: https://stocksnap.io/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
    - name: 3D素材网站
      sites:
        - name: 魔顿网
          description: 国内使用率较高，以C4D为主的资源网站，包含模型、工程、贴图纹理、插件等
          url: http://www.modown.cn/
        - name: 3D溜溜网
          description: Photoshop不需要解释
          url: https://www.3d66.com/
        - name: 知末网
          description: Photoshop不需要解释
          url: https://www.znzmo.com/
        - name: Illustrator
          description: 矢量图形和插图。
          url: https://www.adobe.com/cn/products/illustrator/
        - name: indesign
          description: 页面设计、布局和出版。
          url: http://www.adobe.com/cn/products/indesign.html
        - name: cinema-4d
          description: Cinema 4D is the perfect package for all 3D artists who want to achieve breathtaking results fast and hassle-free.
          url: https://www.maxon.net/en/products/cinema-4d/overview/
        - name: 3ds-max
          description: 3D modeling, animation, and rendering software
          url: https://www.autodesk.com/products/3ds-max/overview
        - name: Blender
          description: Blender is the free and open source 3D creation suite.
          url: https://www.blender.org/
    - name: 界面设计
      sites:
        - name: Adobe XD
          description: Introducing Adobe XD. Design. Prototype. Experience.
          url: http://www.adobe.com/products/xd.html
        - name: invisionapp
          description: Powerful design prototyping tools
          url: https://www.invisionapp.com/
        - name: marvelapp
          description: Simple design, prototyping and collaboration
          url: https://marvelapp.com/
        - name: Muse CC
          description: 无需利用编码即可进行网站设计。
          url: https://creative.adobe.com/zh-cn/products/download/muse
        - name: figma
          description: Design, prototype, and gather feedback all in one place with Figma.
          url: https://www.figma.com/
    - name: 交互动效
      sites:
        - name: Adobe After Effects CC
          description: 电影般的视觉效果和动态图形。
          url: https://www.adobe.com/cn/products/aftereffects/
        - name: principle
          description: Animate Your Ideas, Design Better Apps
          url: http://principleformac.com/
        - name: flinto
          description: Flinto is a Mac app used by top designers around the world to create interactive and animated prototypes of their app designs.
          url: https://www.flinto.com/
        - name: framer
          description: Design everything from detailed icons to high-fidelity interactions—all in one place.
          url: https://framer.com/
        - name: ProtoPie
          description: 高保真交互原型设计
          url: http://www.protopie.cn/
    - name: 在线配色
      sites:
        - name: khroma
          description: Khroma is the fastest way to discover, search, and save color combos you'll want to use.
          url: http://khroma.co/generator/
        - name: uigradients
          description: Beautiful colored gradients
          url: https://uigradients.com
        - name: gradients
          description: Curated gradients for designers and developers
          url: http://gradients.io/
        - name: Coolest
          description: Coolest handpicked Gradient Hues for your next super ⚡ amazing stuff
          url: https://webkul.github.io/coolhue/
        - name: webgradients
          description: WebGradients is a free collection of 180 linear gradients that you can use as content backdrops in any part of your website.
          url: https://webgradients.com/
        - name: grabient
          description: 2017 Grabient by unfold
          url: https://www.grabient.com/
        - name: thedayscolor
          description: The daily color digest
          url: http://www.thedayscolor.com/
        - name: flatuicolors
          description: Copy Paste Color Pallette from Flat UI Theme
          url: http://flatuicolors.com/
        - name: coolors
          description: The super fast color schemes generator!
          url: https://coolors.co/
        - name: colorhunt
          description: Beautiful Color Palettes
          url: http://www.colorhunt.co/
        - name: Adobe Color CC
          description: Create color schemes with the color wheel or browse thousands of color combinations from the Color community.
          url: https://color.adobe.com/zh/create/color-wheel
        - name: flatuicolorpicker
          description: Best Flat Colors For UI Design
          url: http://www.flatuicolorpicker.com/
        - name: trianglify
          description: Trianglify Generator
          url: http://qrohlf.com/trianglify-generator/
        - name: klart
          description: Beautiful colors and designs to your inbox every week
          url: https://klart.co/colors/
        - name: vanschneider
          description: Color Claim was created in 2012 by Tobias van Schneider with the goal to collect & combine unique colors for my future projects.
          url: http://www.vanschneider.com/colors
    - name: 在线工具
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
        - name: goqr
          description: create QR codes for free (Logo, T-Shirt, vCard, EPS)
          url: http://goqr.me/
        - name: ezgif
          description: simple online GIF maker and toolset for basic animated GIF editing.
          url: https://ezgif.com
        - name: Android 9 patch
          description: Android 9-patch shadow generator fully customizable shadows
          url: http://inloop.github.io/shadow4android/
        - name: screen sizes
          description: Viewport Sizes and Pixel Densities for Popular Devices
          url: http://screensiz.es/
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com
    - name: 设计规范
      sites:
        - name: Design Guidelines
          description: Design Guidelines — The way products are built.
          url: http://designguidelines.co/
        - name: Awesome design systems
          description: A collection of awesome design systems
          url: https://github.com/alexpate/awesome-design-systems
        - name: Material Design
          description: Introduction - Material Design
          url: https://material.io/guidelines/
        - name: Human Interface Guidelines
          description: Human Interface Guidelines iOS
          url: https://developer.apple.com/ios/human-interface-guidelines
        - name: Photoshop Etiquette
          description: PS礼仪-WEB设计指南
          url: http://viggoz.com/photoshopetiquette/
    - name: 视频教程
      sites:
        - name: Photoshop Lady
          description: Your Favourite Photoshop Tutorials in One Place
          url: http://www.photoshoplady.com/
        - name: doyoudo
          description: 创意设计软件学习平台
          url: http://doyoudo.com/
        - name: 没位道
          description: WEB UI免费视频公开课
          url: http://www.c945.com/web-ui-tutorial/
        - name: 慕课网
          description: 程序员的梦工厂（有UI课程）
          url: https://www.imooc.com/
    - name: 设计文章
      sites:
        - name: Web Design Ledger
          description: Web Design Blog
          url: https://webdesignledger.com
    - name: 设计电台
      sites:
        - name: UX Coffee
          description: 《UX Coffee 设计咖》是一档关于用户体验的播客节目。我们邀请来自硅谷和国内的学者和职人来聊聊「产品设计」、「用户体验」和「个人成长」。
          url: http://uxcoffee.co/
        - name: Anyway.FM
          description: 设计杂谈 • UI 设计师 JJ 和 Leon 主播的设计播客
          url: https://anyway.fm/
        - name: 异能电台
          description: 将全宇宙设计师的故事讲给你听。
          url: https://www.yineng.fm
    - name: 交互设计
      sites:
        - name: Little Big Details
          description: Little Big Details is a curated collection of the finer details of design, updated every day.
          url: http://littlebigdetails.com/
        - name: Smashing Magazine
          description: Below you’ll find the best tips to take not only your UX design process but also the experiences you craft to the next level.
          url: https://www.smashingmagazine.com/category/user-experience
        - name: nngroup
          description: Evidence-Based User Experience Research, Training, and Consulting
          url: https://www.nngroup.com/articles/
        - name: Boxes and Arrows
          description: Boxes and Arrows is devoted to the practice, innovation, and discussion of design; including graphic design, interaction design, information architecture and the design of business.
          url: http://boxesandarrows.com/
        - name: UX Design Weekly
          description: get a hand picked list of the best user experience design links every week.
          url: http://uxdesignweekly.com/
        - name: UX Ren
          description: 用户体验人的专业社区
          url: http://uxren.cn/
    - name: UED团队
      sites:
        - name: Airbnb Design
          description: Airbnb Design
          url: https://airbnb.design
        - name: Facebook Design
          description: Facebook Design
          url: http://facebook.design/
        - name: Google Design
          description: Google Design
          url: https://design.google/
        - name: eico design
          description: 数字化咨询与产品专家
          url: http://eicodesign.com/
        - name: nice design
          description: nicedesign奈思设计是领先的用户体验设计与互联网品牌建设公司
          url: http://www.niceui.cn/
        - name: 腾讯CDC
          description: 腾讯CDC关注于互联网视觉设计、交互设计、用户研究、前端开发。
          url: http://cdc.tencent.com/
        - name: TGideas
          description: TGideas隶属于腾讯公司互动娱乐业务系统的专业推广类设计团队
          url: http://tgideas.qq.com/
        - name: ISUX
          description: 腾讯社交用户体验设计部
          url: https://isux.tencent.com/
        - name: MXD
          description: 腾讯MIG无线互联网事业群设计团队
          url: http://mxd.tencent.com/
        - name: Aliued
          description: 阿里巴巴国际UED团队
          url: http://www.aliued.com/
        - name: U一点
          description: 阿里巴巴（中国站）用户体验设计部博客U一点设计 UED团队
          url: http://www.aliued.cn/
        - name: 网易uedc
          description: 网易用户体验设计中心（User Experience Design Center）
          url: http://uedc.163.com/
        - name: 百度用户体验中心
          description: 百度用户体验中心
          url: http://ued.baidu.com/
        - name: 京东设计中心
          description: 京东设计中心
          url: http://jdc.jd.com/
        - name: 百度企业产品用户体验中心
          description: 百度企业产品用户体验中心
          url: http://eux.baidu.com/
        - name: 携程设计委员会
          description: 携程设计委员会-Ctrip Design Committee
          url: http://ued.ctrip.com/
